### ISSUE TITLE
Register at https://packagist.org

### ISSUE THREAD

**Issue by holtkamp** [dpovshed/octopus#13]
Currently this repository needs to be added to `composer.json` in order to be able to install it. Registering at https://packagist.org can prevent this.

@dpovshed not sure if you are "open" for this?

**Comment by dpovshed** [comment]
I found this idea very useful! However, package cannot be added because of 
_"...The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace..."_
So lets tune namespace then! Any suggestions?

**Comment by holtkamp** [comment]
Aah, what a pity that "octopus" is already taken 😢

What about using the scientific name "octopoda" as organization? In that case the package will become: `octopoda/octopus`... Not very creative though 😄 

Maybe more inspiration on: https://en.wikipedia.org/wiki/Octopus

**Comment by dpovshed** [comment]
Lets think a bit. From the wiki I liked 'Octopus vulgaris' very much :)

**Comment by dpovshed** [comment]
Yes, seems like **octopoda** is fair enough

**Comment by dpovshed** [comment]
Well, here we are: https://packagist.org/packages/octopoda/octopus
